### ISSUE TITLE
broken image ?

### ISSUE THREAD

**Issue by sfeher-paymentus** [matisku/tig-stack#2]
In the latest image (2c241b797aff) I can't access the web ui (the connection is closed right away without any response). The moment I've switched to an older image (b66b4dfa1a5e ) it all works fine.

**Comment by matisku** [comment]
Can't confirm. I just did a git clone and `docker-compose up` and everything is running perfectly.

**Comment by matisku** [comment]
All looks fine for me. Closing the issue.
